import BlogId from "@/components/blog/BlogId";
import Scrolltotop from "@/components/scroll/Scrolltotop";
import Head from "next/head";
import Link from "next/link";
import { FaAngleRight } from "react-icons/fa";

const IdPage = ({data}) =>  {
    return(
        <>
        <Head>
        <title>Chirkli-News</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://cdn.shopify.com/s/files/1/0607/7287/6512/files/favicon_d5c9515a-64b4-47af-9ef1-236eddcc39a8_16x16.png?v=1637219740" />
        </Head>
        <main>
        <section id="heading">
          <div className="title">
            <h2>Blog US</h2>
            <div className="link">
              <Link href="/">
                HOME <FaAngleRight />
              </Link>
            </div>
          </div>
        </section>
        {/* <div dangerouslySetInnerHTML={{__html: data.content}}></div> */}
        {/* <BlogId page={data}/> */}
        </main>
        <Scrolltotop/>
        </>
    )
}
export default IdPage;

export const getServerSideProps = async (context) => {
  const res = await fetch(`https://json-server-tan-kappa.vercel.app/blogchirkli/${context.params.blogId}`);
  const data = await res.json();
  console.log(data);
  return{
    props:{
      // data,
    },
  };
};