import Head from "next/head";
import Scrolltotop from "@/components/scroll/Scrolltotop";

export default function Home() {
  return (
    <>
      <Head>
        <title>Reprizo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://cdn.shopify.com/s/files/1/0607/7287/6512/files/favicon_d5c9515a-64b4-47af-9ef1-236eddcc39a8_16x16.png?v=1637219740" />
      </Head>
      <main>
        <h1>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed
          accusantium alias corporis? Consequuntur itaque eos corrupti eaque
          sapiente odio. Corrupti dicta optio, fugiat reiciendis facilis libero
          nihil, sunt doloribus asperiores odio repellat exercitationem iste!
          Porro aperiam, tempora architecto iusto nesciunt perferendis cum
          accusamus ad hic! Eos quod, quam nihil sapiente sint eaque libero
          suscipit molestias, possimus animi itaque cumque perferendis, dolor
          aut corrupti assumenda minima? Molestias, placeat. Delectus earum
          aliquam porro nesciunt iste quidem mollitia aliquid est temporibus
          dicta cum nisi pariatur ipsam officiis doloremque accusamus,
          voluptatibus in ut minima blanditiis? Quod suscipit, labore, accusamus
          nisi facilis assumenda, repellat voluptate consequatur ea sapiente
          recusandae quibusdam ipsa et enim ullam sunt exercitationem eum
          laudantium? Accusantium porro sed assumenda officiis fugit impedit in
          veniam sint?
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed
          accusantium alias corporis? Consequuntur itaque eos corrupti eaque
          sapiente odio. Corrupti dicta optio, fugiat reiciendis facilis libero
          nihil, sunt doloribus asperiores odio repellat exercitationem iste!
          Porro aperiam, tempora architecto iusto nesciunt perferendis cum
          accusamus ad hic! Eos quod, quam nihil sapiente sint eaque libero
          suscipit molestias, possimus animi itaque cumque perferendis, dolor
          aut corrupti assumenda minima? Molestias, placeat. Delectus earum
          aliquam porro nesciunt iste quidem mollitia aliquid est temporibus
          dicta cum nisi pariatur ipsam officiis doloremque accusamus,
          voluptatibus in ut minima blanditiis? Quod suscipit, labore, accusamus
          nisi facilis assumenda, repellat voluptate consequatur ea sapiente
          recusandae quibusdam ipsa et enim ullam sunt exercitationem eum
          laudantium? Accusantium porro sed assumenda officiis fugit impedit in
          veniam sint?
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed
          accusantium alias corporis? Consequuntur itaque eos corrupti eaque
          sapiente odio. Corrupti dicta optio, fugiat reiciendis facilis libero
          nihil, sunt doloribus asperiores odio repellat exercitationem iste!
          Porro aperiam, tempora architecto iusto nesciunt perferendis cum
          accusamus ad hic! Eos quod, quam nihil sapiente sint eaque libero
          suscipit molestias, possimus animi itaque cumque perferendis, dolor
          aut corrupti assumenda minima? Molestias, placeat. Delectus earum
          aliquam porro nesciunt iste quidem mollitia aliquid est temporibus
          dicta cum nisi pariatur ipsam officiis doloremque accusamus,
          voluptatibus in ut minima blanditiis? Quod suscipit, labore, accusamus
          nisi facilis assumenda, repellat voluptate consequatur ea sapiente
          recusandae quibusdam ipsa et enim ullam sunt exercitationem eum
          laudantium? Accusantium porro sed assumenda officiis fugit impedit in
          veniam sint?
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed
          accusantium alias corporis? Consequuntur itaque eos corrupti eaque
          sapiente odio. Corrupti dicta optio, fugiat reiciendis facilis libero
          nihil, sunt doloribus asperiores odio repellat exercitationem iste!
          Porro aperiam, tempora architecto iusto nesciunt perferendis cum
          accusamus ad hic! Eos quod, quam nihil sapiente sint eaque libero
          suscipit molestias, possimus animi itaque cumque perferendis, dolor
          aut corrupti assumenda minima? Molestias, placeat. Delectus earum
          aliquam porro nesciunt iste quidem mollitia aliquid est temporibus
          dicta cum nisi pariatur ipsam officiis doloremque accusamus,
          voluptatibus in ut minima blanditiis? Quod suscipit, labore, accusamus
          nisi facilis assumenda, repellat voluptate consequatur ea sapiente
          recusandae quibusdam ipsa et enim ullam sunt exercitationem eum
          laudantium? Accusantium porro sed assumenda officiis fugit impedit in
          veniam sint?
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed
          accusantium alias corporis? Consequuntur itaque eos corrupti eaque
          sapiente odio. Corrupti dicta optio, fugiat reiciendis facilis libero
          nihil, sunt doloribus asperiores odio repellat exercitationem iste!
          Porro aperiam, tempora architecto iusto nesciunt perferendis cum
          accusamus ad hic! Eos quod, quam nihil sapiente sint eaque libero
          suscipit molestias, possimus animi itaque cumque perferendis, dolor
          aut corrupti assumenda minima? Molestias, placeat. Delectus earum
          aliquam porro nesciunt iste quidem mollitia aliquid est temporibus
          dicta cum nisi pariatur ipsam officiis doloremque accusamus,
          voluptatibus in ut minima blanditiis? Quod suscipit, labore, accusamus
          nisi facilis assumenda, repellat voluptate consequatur ea sapiente
          recusandae quibusdam ipsa et enim ullam sunt exercitationem eum
          laudantium? Accusantium porro sed assumenda officiis fugit impedit in
          veniam sint?
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed
          accusantium alias corporis? Consequuntur itaque eos corrupti eaque
          sapiente odio. Corrupti dicta optio, fugiat reiciendis facilis libero
          nihil, sunt doloribus asperiores odio repellat exercitationem iste!
          Porro aperiam, tempora architecto iusto nesciunt perferendis cum
          accusamus ad hic! Eos quod, quam nihil sapiente sint eaque libero
          suscipit molestias, possimus animi itaque cumque perferendis, dolor
          aut corrupti assumenda minima? Molestias, placeat. Delectus earum
          aliquam porro nesciunt iste quidem mollitia aliquid est temporibus
          dicta cum nisi pariatur ipsam officiis doloremque accusamus,
          voluptatibus in ut minima blanditiis? Quod suscipit, labore, accusamus
          nisi facilis assumenda, repellat voluptate consequatur ea sapiente
          recusandae quibusdam ipsa et enim ullam sunt exercitationem eum
          laudantium? Accusantium porro sed assumenda officiis fugit impedit in
          veniam sint?</h1>
  
      </main>
      <Scrolltotop/>
    </>
  );
}
