import Scrolltotop from "@/components/scroll/Scrolltotop";
import Head from "next/head";


export default function User() {
    return(
        <>
        <Head>
        <title>Chirkli-User</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://cdn.shopify.com/s/files/1/0607/7287/6512/files/favicon_d5c9515a-64b4-47af-9ef1-236eddcc39a8_16x16.png?v=1637219740" />
        </Head>
        <main>
            <h1>Bura menim user hissemdir</h1>
        </main>
        <Scrolltotop/>
        </>
    )
}